name: beaver_cli
version: 0.1.0
description: Command line interface for the Beaver.

author: Fluidic Team <dev@fluidic.io>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  foo_bar: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
