name: beaver_store
description: Store for beaver configuration and task's result.
version: 0.1.0
author: Fluidic Team <dev@fluidic.io>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  beaver_task:
    path: ../beaver_task
  beaver_trigger_handler:
    path: ../beaver_trigger_handler
  gcloud: '>=0.3.0 <0.4.0'
  path: '>=1.3.9 <1.4.0'
  quiver_collection: '>=1.0.0 <1.1.0'
  quiver_iterables: '>=1.0.0 <1.1.0'
  yaml: '>=2.1.10 <2.2.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
