name: beaver_frontend_gae
description: GAE frontend for beaver ci.
version: 0.1.0
author: Fluidic Team <dev@fluidic.io>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  beaver_api:
    path: ../beaver_api
  beaver_trigger_handler:
    path: ../beaver_trigger_handler
  shelf: '>=0.6.5+3 <0.7.0'
  shelf_route: '>=0.14.2 <0.15.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
