project_name: test
description: "hello world"
cloud_type: "gcloud"
service_account_credentials_path: "/Users/maniagoon/.gcloud/my-project.json"

triggers:
  - url: "https://github.com/fluidic/beaver"
    type: github
    token: token_for_test
    events: ["github_event_pull_request_opened"]
    task:
      name: download
      args: ["trigger:pull_request.patch_url", "."]

# dart beaver.dart test -d '{"action":"opened", "pull_request": {"patch_url": "https://github.com/fluidic/beaver/pull/34.patch"}, "repository": {"html_url": "https://github.com/fluidic/beaver"}}' -e pull_request