project_name: test
description: "hello world"

# FIXME: Remove after implementing setup(init) cli_command.
cloud_type: gcloud
zone: us-central1-a
cloud_project_name: beaver-ci

triggers:
  - name: build_by_push
    url: "https://github.com/fluidic/beaver"
    type: github
    events: ["pull_request"]
    task:
      - name: download
        args: ["trigger:payload.pull_request.patch_url", "."]
# dart beaver.dart test -d '{"action":"opened", "pull_request": {"patch_url": "https://github.com/fluidic/beaver/pull/34.patch"}, "repository": {"html_url": "https://github.com/fluidic/beaver"}}' -e pull_request
  - name: daily_build
    type: cron
    task:
      - name: download
        args: ["https://raw.githubusercontent.com/fluidic/beaver/master/beaver_trigger_handler/README.md", "."]
