name: beaver_gcloud
description: GCloud helpers
version: 0.1.0
author: Fluidic Team <dev@fluidic.io>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  gcloud: '>=0.3.0 <0.4.0'
  googleapis: any
  googleapis_auth: any
  uuid: '>=0.5.3 <0.6.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
