name: demo
description: A demo Dart package
version: 0.1.0
author: Fluidic Team <dev@fluidic.io>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  beaver_core:
    path: ../beaver_core
  test: '>=0.12.0 <0.13.0'
