project_name: test
description: "hello world"

# FIXME: Remove after implementing setup(init) command.
cloud_type: gcloud
zone: us-central1-a
cloud_project_name: beaver-ci

triggers:
  - url: "https://github.com/fluidic/beaver"
    type: github
    token: token_for_test
    events: ["github_event_create_branch"]
    task:
      - name: download
        args: ["https://raw.githubusercontent.com/fluidic/beaver/master/beaver_trigger_handler/README.md", "."]
